/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppUsersRouteImport } from './routes/app.users'
import { Route as AppTransactionsRouteImport } from './routes/app.transactions'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppRolesRouteImport } from './routes/app.roles'
import { Route as AppReportsRouteImport } from './routes/app.reports'
import { Route as AppRcaRouteImport } from './routes/app.rca'
import { Route as AppNotificationsRouteImport } from './routes/app.notifications'
import { Route as AppInvestigationsRouteImport } from './routes/app.investigations'
import { Route as AppInvestigationRouteImport } from './routes/app.investigation'
import { Route as AppIncidentsRouteImport } from './routes/app.incidents'
import { Route as AppHelpRouteImport } from './routes/app.help'
import { Route as AppFraudRouteImport } from './routes/app.fraud'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppAuditRouteImport } from './routes/app.audit'
import { Route as AppAssistantRouteImport } from './routes/app.assistant'
import { Route as AppArchitectureRouteImport } from './routes/app.architecture'
import { Route as AppAnomaliesRouteImport } from './routes/app.anomalies'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppTransactionsRoute = AppTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppRolesRoute = AppRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppRcaRoute = AppRcaRouteImport.update({
  id: '/rca',
  path: '/rca',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppInvestigationsRoute = AppInvestigationsRouteImport.update({
  id: '/investigations',
  path: '/investigations',
  getParentRoute: () => AppRoute,
} as any)
const AppInvestigationRoute = AppInvestigationRouteImport.update({
  id: '/investigation',
  path: '/investigation',
  getParentRoute: () => AppRoute,
} as any)
const AppIncidentsRoute = AppIncidentsRouteImport.update({
  id: '/incidents',
  path: '/incidents',
  getParentRoute: () => AppRoute,
} as any)
const AppHelpRoute = AppHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => AppRoute,
} as any)
const AppFraudRoute = AppFraudRouteImport.update({
  id: '/fraud',
  path: '/fraud',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditRoute = AppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppRoute,
} as any)
const AppAssistantRoute = AppAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => AppRoute,
} as any)
const AppArchitectureRoute = AppArchitectureRouteImport.update({
  id: '/architecture',
  path: '/architecture',
  getParentRoute: () => AppRoute,
} as any)
const AppAnomaliesRoute = AppAnomaliesRouteImport.update({
  id: '/anomalies',
  path: '/anomalies',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/anomalies': typeof AppAnomaliesRoute
  '/app/architecture': typeof AppArchitectureRoute
  '/app/assistant': typeof AppAssistantRoute
  '/app/audit': typeof AppAuditRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/fraud': typeof AppFraudRoute
  '/app/help': typeof AppHelpRoute
  '/app/incidents': typeof AppIncidentsRoute
  '/app/investigation': typeof AppInvestigationRoute
  '/app/investigations': typeof AppInvestigationsRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/rca': typeof AppRcaRoute
  '/app/reports': typeof AppReportsRoute
  '/app/roles': typeof AppRolesRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/transactions': typeof AppTransactionsRoute
  '/app/users': typeof AppUsersRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/app/anomalies': typeof AppAnomaliesRoute
  '/app/architecture': typeof AppArchitectureRoute
  '/app/assistant': typeof AppAssistantRoute
  '/app/audit': typeof AppAuditRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/fraud': typeof AppFraudRoute
  '/app/help': typeof AppHelpRoute
  '/app/incidents': typeof AppIncidentsRoute
  '/app/investigation': typeof AppInvestigationRoute
  '/app/investigations': typeof AppInvestigationsRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/rca': typeof AppRcaRoute
  '/app/reports': typeof AppReportsRoute
  '/app/roles': typeof AppRolesRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/transactions': typeof AppTransactionsRoute
  '/app/users': typeof AppUsersRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/anomalies': typeof AppAnomaliesRoute
  '/app/architecture': typeof AppArchitectureRoute
  '/app/assistant': typeof AppAssistantRoute
  '/app/audit': typeof AppAuditRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/fraud': typeof AppFraudRoute
  '/app/help': typeof AppHelpRoute
  '/app/incidents': typeof AppIncidentsRoute
  '/app/investigation': typeof AppInvestigationRoute
  '/app/investigations': typeof AppInvestigationsRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/rca': typeof AppRcaRoute
  '/app/reports': typeof AppReportsRoute
  '/app/roles': typeof AppRolesRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/transactions': typeof AppTransactionsRoute
  '/app/users': typeof AppUsersRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/app/anomalies'
    | '/app/architecture'
    | '/app/assistant'
    | '/app/audit'
    | '/app/dashboard'
    | '/app/fraud'
    | '/app/help'
    | '/app/incidents'
    | '/app/investigation'
    | '/app/investigations'
    | '/app/notifications'
    | '/app/rca'
    | '/app/reports'
    | '/app/roles'
    | '/app/settings'
    | '/app/transactions'
    | '/app/users'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/app/anomalies'
    | '/app/architecture'
    | '/app/assistant'
    | '/app/audit'
    | '/app/dashboard'
    | '/app/fraud'
    | '/app/help'
    | '/app/incidents'
    | '/app/investigation'
    | '/app/investigations'
    | '/app/notifications'
    | '/app/rca'
    | '/app/reports'
    | '/app/roles'
    | '/app/settings'
    | '/app/transactions'
    | '/app/users'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/app/anomalies'
    | '/app/architecture'
    | '/app/assistant'
    | '/app/audit'
    | '/app/dashboard'
    | '/app/fraud'
    | '/app/help'
    | '/app/incidents'
    | '/app/investigation'
    | '/app/investigations'
    | '/app/notifications'
    | '/app/rca'
    | '/app/reports'
    | '/app/roles'
    | '/app/settings'
    | '/app/transactions'
    | '/app/users'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/users': {
      id: '/app/users'
      path: '/users'
      fullPath: '/app/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/transactions': {
      id: '/app/transactions'
      path: '/transactions'
      fullPath: '/app/transactions'
      preLoaderRoute: typeof AppTransactionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/roles': {
      id: '/app/roles'
      path: '/roles'
      fullPath: '/app/roles'
      preLoaderRoute: typeof AppRolesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports': {
      id: '/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/rca': {
      id: '/app/rca'
      path: '/rca'
      fullPath: '/app/rca'
      preLoaderRoute: typeof AppRcaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notifications': {
      id: '/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/investigations': {
      id: '/app/investigations'
      path: '/investigations'
      fullPath: '/app/investigations'
      preLoaderRoute: typeof AppInvestigationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/investigation': {
      id: '/app/investigation'
      path: '/investigation'
      fullPath: '/app/investigation'
      preLoaderRoute: typeof AppInvestigationRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/incidents': {
      id: '/app/incidents'
      path: '/incidents'
      fullPath: '/app/incidents'
      preLoaderRoute: typeof AppIncidentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/help': {
      id: '/app/help'
      path: '/help'
      fullPath: '/app/help'
      preLoaderRoute: typeof AppHelpRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/fraud': {
      id: '/app/fraud'
      path: '/fraud'
      fullPath: '/app/fraud'
      preLoaderRoute: typeof AppFraudRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/audit': {
      id: '/app/audit'
      path: '/audit'
      fullPath: '/app/audit'
      preLoaderRoute: typeof AppAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/assistant': {
      id: '/app/assistant'
      path: '/assistant'
      fullPath: '/app/assistant'
      preLoaderRoute: typeof AppAssistantRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/architecture': {
      id: '/app/architecture'
      path: '/architecture'
      fullPath: '/app/architecture'
      preLoaderRoute: typeof AppArchitectureRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/anomalies': {
      id: '/app/anomalies'
      path: '/anomalies'
      fullPath: '/app/anomalies'
      preLoaderRoute: typeof AppAnomaliesRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAnomaliesRoute: typeof AppAnomaliesRoute
  AppArchitectureRoute: typeof AppArchitectureRoute
  AppAssistantRoute: typeof AppAssistantRoute
  AppAuditRoute: typeof AppAuditRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppFraudRoute: typeof AppFraudRoute
  AppHelpRoute: typeof AppHelpRoute
  AppIncidentsRoute: typeof AppIncidentsRoute
  AppInvestigationRoute: typeof AppInvestigationRoute
  AppInvestigationsRoute: typeof AppInvestigationsRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppRcaRoute: typeof AppRcaRoute
  AppReportsRoute: typeof AppReportsRoute
  AppRolesRoute: typeof AppRolesRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTransactionsRoute: typeof AppTransactionsRoute
  AppUsersRoute: typeof AppUsersRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnomaliesRoute: AppAnomaliesRoute,
  AppArchitectureRoute: AppArchitectureRoute,
  AppAssistantRoute: AppAssistantRoute,
  AppAuditRoute: AppAuditRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppFraudRoute: AppFraudRoute,
  AppHelpRoute: AppHelpRoute,
  AppIncidentsRoute: AppIncidentsRoute,
  AppInvestigationRoute: AppInvestigationRoute,
  AppInvestigationsRoute: AppInvestigationsRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppRcaRoute: AppRcaRoute,
  AppReportsRoute: AppReportsRoute,
  AppRolesRoute: AppRolesRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTransactionsRoute: AppTransactionsRoute,
  AppUsersRoute: AppUsersRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
